name: Remove from Good First Issue
on:
  issues:
    types:
      - closed
jobs:
  add-to-good-first-issues:
    if: contains(github.event.issue.labels.*.name, 'good first issue')
    runs-on: ubuntu-latest
    steps:
      - name: Remove issue from Projects
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_ORG_ADMIN}}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: 4
        run: |
          item_id="$( gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($project:ID!, $issue:ID!) {
              deleteProjectNextItem(input: {projectId: $project, itemId: $pr}) {
                deletedItemId
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID"
          
