name: Add to Good First Issue
on:
  issues:
    types:
      - labeled
jobs:
  add-to-good-first-issues:
    if: github.event.label.name == 'good first issue'
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to project
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_ORG_ADMIN}}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: PN_kwDOAPpDts0UBA
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $pr}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$ISSUE_ID --jq '.data.addProjectNextItem.projectNextItem.id'
          
          echo 'Added the issue to the First Good Issue project'
