name: Remove from Good First Issue
on:
  issues:
    types:
      - closed
jobs:
  remove-from-good-first-issues:
    if: contains(github.event.issue.labels.*.name, 'good first issue')
    runs-on: ubuntu-latest
    steps:
      - name: Remove issue from Projects
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_ORG_ADMIN}}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: PN_kwDOAPpDts0UBA
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($project:ID!, $issue:ID!) {
              deleteProjectNextItem(input: {projectId: $project, itemId: $pr}) {
                deletedItemId
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID
            
          echo 'Removed the issue to the First Good Issue project'
