name: Add to Hot Issues/PRs
on:
  pull_request_target:
    types: 
      - opened
  issues:
    types:
      - opened
jobs:
  add-to-good-first-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue/PR to projects
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_ORG_ADMIN}}
          ISSUE_ID: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          PROJECT_ID: PN_kwDOAPpDts0fAA
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $pr}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$ISSUE_ID
          
          echo 'Added the issue/pr to the Hot Issues/PRs'
